### ISSUE TITLE
Clicking even when looping between zero crossings

### ISSUE THREAD

**Issue by xnakos** [rncbc/samplv1#12]
Greetings, Rui and lurkers!

Investigating `samplv1`, I am not able to produce a click-less looping sound, based on a simple sample. I created the sample using `qtractor` and a simple `amsynth` patch. Using `audacity` I selected a nice region `at zero crossings`, which I believed should yield a click-less sound when looping over (please tell me in case I have totally misunderstood something, since I have just started playing with sampling). I then loaded the sample to `samplv1`, using the at-zero-crossings sample numbers as `start` and `end`, and recorded a single note using `qtractor`. I finally exported the audio. The input sample and exported audio are here: [sample-and-export.zip](https://github.com/rncbc/samplv1/files/1503035/sample-and-export.zip). Clicks are audible in the exported audio.

This is the waveform of the input sample and the selected at-zero-crossings region (I selected ten periods):

![sample-c4-stereo](https://user-images.githubusercontent.com/1213128/33230279-e2705d2e-d1e8-11e7-96a6-6afacc075324.png)

This is the configuration of `samplv1`:

![samplv1](https://user-images.githubusercontent.com/1213128/33230292-2515bca0-d1e9-11e7-99c0-b8c6a912d6fc.png)

These are parts of the exported audio (normalized). I have marked what I believe are anomalies:

![export-anomaly](https://user-images.githubusercontent.com/1213128/33230317-ac3c0158-d1e9-11e7-8209-a23408c7280c.png)

![export-anomaly-period](https://user-images.githubusercontent.com/1213128/33230309-785f4d4a-d1e9-11e7-96ff-d66b0212ea77.png)

Is there an error on my part or is this a bug?

**Comment by rncbc** [comment]
yes, probably it's a more like a feature turned into a bug :)

fact is that samplv1 searches for its own zero-crossings too, on its own at the loop start/end points. 

however, it **also** applies a forced micro-fade-in and -out at the loop-start and -end resp. over a fixed number of frames (32 samples) independently of current sample-rate.

it is this micro-fade-in/out that you see as anomalies on the waveform graphics above.

i'll see whether this micro-fade-io-sh*tty-artifacts may be axed *tout-couer* as it nowadays seems like just an overzealous and naive design and engineering mistake. ;)

cheers && thanks

**Comment by rncbc** [comment]
good news are micro-fade-in/outs on loop points are now gone ( https://github.com/rncbc/samplv1/commit/c2265628f6ad7f84c702708c1f9c5dde82047d3d )
bad news are that other, more atonal but looped samples may now click harder than before :(
cheers

**Comment by xnakos** [comment]
Thank you, Rui, for the fast response! I cannot test it right now, but your choice seems excellent. Easy loops should loop easily, I guess. I will test it as soon as possible. In case you have already tried the attached or a similar sample and found it fine, you could close the current issue. If not, I will do so after testing it.

Keep on rocking in the free and open-source world!

**Comment by xnakos** [comment]
Clicking is gone. Closing. Thank you!
