### ISSUE TITLE
Pitch as phase vocoder 

### ISSUE THREAD

**Issue by m4l3z** [rncbc/samplv1#14]
Hey Rui, hope you're doing fine,

I was wondering about the possibility to add a second algorithm (or replace the current implementation) for pitch shifting that would use a phase vocoder instead of playback rate. I heard of [soundtouch](https://www.surina.net/soundtouch/) LGPL and[ rubberband ](https://breakfastquay.com/rubberband/) GPL The user would have the possibility to choose what the midi notes will modify between :
- speed
- pitch
- playback rate (speed & pitch)
The main goal is to be able to preserve the bpm of the rhythmic elements in the samples but I think this could lead to a lot of happy accidents/experimentation too. 
Tell me what you think about that idea and how realistic it is, 

Take care,

**Comment by rncbc** [comment]
believe me, it all has been thought and tried before, to split sample wavetables over higher and lower octaves at least, using soundtouch, rubberband and quite a few others, even a _homebrew_ PSOLA , with mixed and disparate results; quite frankly most of the results were all far from just good enough, so it was all just ditched for a while.

**Comment by m4l3z** [comment]
Alright, if none of these approaches made viable results I understand the frustration, I naively didn't expect the two mentioned libs to be so problematic to use. 
Thanks for the quick feedback !

**Comment by rncbc** [comment]
they are not problematic, they work fine but some samples sounds work better with some and bad with with others and vice-versa.

anyway, i'll try to revisit all this in the future--the subject is not ditched for good ;)
thanks

**Comment by rncbc** [comment]
there are news over here :)
check this out: samplv1 >= 0.9.16.32git.https://github.com/rncbc/samplv1/commit/66aeb5
cheers
