### ISSUE TITLE
Allow selecting In and Out points in a sample

### ISSUE THREAD

**Issue by unfa** [rncbc/samplv1#16]
I'd like to load up a long sample and select just a short part from it to be played back.
I tried using the loop markers but they do a different thing. I first thought the are just for that.

I think it'd be great to have a separate "In/Out" range markers to select a part in the sample to be used.

Also being able to zoom in/out in the sample waveform preview could be a great help to precisely select the In/Out points.

I know I could prepare precisely cut samples to be loaded into Samplv1, but being able to do this live is adding much versatility to the plugin, also be cause one could automate the In/Out point positions to effectively change the sound between each played note.

**Comment by rncbc** [comment]
hello unfa, this has been asked indeed way too many times, but the same answer and only goes in return: nope :)
please edit your sample before loading into samplv1; use an audio file editor for just that, audacity comes always in first. but you can choose any other to trim the sample--you even get resource (read memory aka. ram) savings with that procedure, coz samplv1 loads the whole sample image into live memory anyway.
hyu.
cheers

**Comment by unfa** [comment]
Thank you. I understand that approach, but I still think that this functionality would be beneficial to creative freedom, especially with automation.

Also I think that loading 30 or 100 more MB of PCM data into RAM is not big deal in modern systems boasting 8 GB of RAM or even more. If low memory usage is key - sure but why force that on the users?

**Comment by rncbc** [comment]
sorry, but that setting (as the loop points) cannot be _automateable_--if there are some host or DAW that you know that does it, then it's doing it wrong, glitch-prone and above all it won't ever be sample accurate as it probably advertises ;)
byee

**Comment by unfa** [comment]
The problem is - even when I try to truncate the sample before loading it into Samplv1  - I sill often have to redo that a few times as in real use it works differently than I expected.

In such case I also have to reset my loop marker swich might be tricky.

I think LSP's Sampler has the truncation options but it doesn't have looping functionality on the other hand. Which makes it not suitable for sustained melodic instruments.

**Comment by mxmilkiib** [comment]
Start and end points would be handy for faff free topping and tailing. The Akai S900 has a Discard feature that "...eliminates those portions of the sample before the start point and after the end point. Since you do not hear these parts of the sample, discarding the sample past these points will save memory." Possibly a similar system, manual or automatic, could work in samplv1?

Start/end point automation is nice and all but hard and not so old-school.

**Comment by rncbc** [comment]
hi, 

starting from today's latest  v0.9.1.14git.[f98e37](https://github.com/rncbc/samplv1/commit/f98e37b),  sample start point (offset) support is now a reality.

cheers

**Comment by unfa** [comment]
Yay! Many thanks, @rncbc !

**Comment by rncbc** [comment]
things are getting better (hopefiully)... just check 0.9.1.21git.[667a8](https://github.com/rncbc/samplv1/commit/667a81) and beyhond... ;)
