### ISSUE TITLE
unstable playback

### ISSUE THREAD

**Issue by tjingboem** [rncbc/samplv1#18]
Still running Samplv1 in debug mode, i found that the notes played back with the sampler are not stable. There is some kind of flutter.

I hope you can replicate this issue. Here is the saw wave i used: 
[zaag.wav.zip](https://github.com/rncbc/samplv1/files/1848628/zaag.wav.zip)
and i made a video about the issue:
[unstable_notes-2018-03-26_18.15.53.mp4.zip](https://github.com/rncbc/samplv1/files/1848630/unstable_notes-2018-03-26_18.15.53.mp4.zip)

First i play the notes with the Tuning Tab ticked, then unticked. Both examples are made with the standard 12 notes in an octave.

We did not notice this behavior before as we are using ambient and complex rhythmic patterns with Samplv1.

**Comment by rncbc** [comment]
im afraid i don't quite reproduce this said _fluttering_ ...
have you check whether the modwheel (CC#1) is set to zero position?
cheers

**Comment by tjingboem** [comment]
This is weird - i even checked my soundcard :p 
And a different jack-keyboard...

Issue still there!
i made a new video, showing this issue again, but now i do see somewhat of a pattern: when the tone is in a perfect octave, all goes well. When i use different notes, the issue starts. Also notice that when the note is higher, the frequency of the 'flutter' increases as well. 
[unstable_notes2-2018-03-26_20.28.53.mp4.zip](https://github.com/rncbc/samplv1/files/1849077/unstable_notes2-2018-03-26_20.28.53.mp4.zip)

The Tuning Tab is set to off, and as you can see in the video, i have every possible modulation set to 0. Even tried different settings of the LFO but as you can see, it has amplitude 0 on the signal.
In a few days i will have access to a second computer, that runs the same Linux Mint 18.3. I will check it there also...

**Comment by tjingboem** [comment]
I think i have narrowed down the issue regarding the flutter.
Please have a look at the video: 
[unstable_notes5-2018-03-31_21.30.59.mp4.zip](https://github.com/rncbc/samplv1/files/1865838/unstable_notes5-2018-03-31_21.30.59.mp4.zip)

This time, in Audacity, i generated a sine tone of 3 seconds, so i could better see if there was something  happening with the sgnal when it was played by Samplv1.
[sinus.wav.zip](https://github.com/rncbc/samplv1/files/1865840/sinus.wav.zip)

This test exposes several issues, but 2 pretty important:
1. the sine tone in Samplv1 creates a 3rd harmonic - although with much less amplitude. The frequency of this  'distortion' is 3 x higher then the base sine tone.
2. when Samplv1 goes into his loop, some kind of click is introduced. This click smears all over the frequency spectrum and follows the rhythm of the loop. You can see this at 30 sec of the video, where i make the loop shorter: the click becomes faster with the same notes. At 50 sec. i make the loop bigger, and the clicks appear at a lower rate.
So this is related.

I tried again with the saw wave and i get to the same conclusion. The unstable tones of Samplv1 are produced by the loop. And this is what i was referring to as 'flutter'. 
I think this issue can be avoided when the end of the loop gets a fade out and the begin of the loop gets a fade in.
A few days back i created a ticket for this in Sourceforges' Tickets: https://sourceforge.net/p/samplv1/tickets/10/

**Comment by tjingboem** [comment]
i did some research with an opcode from Csound, flooper2, which allows giving a fade in/fade out time value, just to measure how he was looping.
I must say that, using the sine test as above in Samplv1, i only get a decent loop when the time value of the fades = 0.05. Shorter values produce a click, longer values produce some sort of whining - or flutter as i was referring to all the time - when the loops goes into his loop.

The same sine that was used in the Samplv1 test above did NOT create a 3rd harmonic however.

**Comment by rncbc** [comment]
hi, thanks for your research and quest; however micro-fade-ins/outs on loop-points was once in place but dropped some time ago in favor to zero-crossing detection--see #12.
fact is none are complete _click-free_ but the later seems to have a little bit of better results in the general cases.
cheers

**Comment by tjingboem** [comment]
ouch - that hurts :)

I guess that is the end conclusion...
