### ISSUE TITLE
NSM error

### ISSUE THREAD

**Issue by tjingboem** [rncbc/samplv1#23]
Working on the manual for Samplv1 (https://github.com/rncbc/samplv1/wiki/User-Manual), i try to open Samplv1 in NSM.  I tried it twice.
i get this error:
13:41:13 Listing sessions
13:41:16 Opening session ggg
13:41:16 Waiting for announce messages from clients
13:41:16 Launching samplv1
13:41:17 Client samplv1 died unexpectedly.
13:41:21 Done. 0 out of 1 clients announced within the initialization grace period
13:41:21 Waiting for clients to reply to commands
13:41:22 Done waiting
13:41:22 Loaded.
13:41:48 Launching samplv1
13:41:49 Client samplv1 died unexpectedly.

Personally i do not use and care too much for NSM, but i'd thought i'd mention it to you.

**Comment by rncbc** [comment]
which NSM session manager?
is jackd started before you launch the session?
is the session old or a brand new?
note that old saved NSM-sessions that refer to not-anymore-existing samplv1_jack paths won't run, ever ;)

**Comment by tjingboem** [comment]
solved.
When adding a new client in NSM it is not possible to go to find a program so i wrote: samplv1
Turned out to be: samplv1_jack
than everything works.
