### ISSUE TITLE
harmonics appear

### ISSUE THREAD

**Issue by tjingboem** [rncbc/samplv1#24]
3th, 5th, 7th harmonics appear when i play a clean sine sample at the rootkey (and others).

What i did:

1. generated a 3 second sine with Audacity. This looks totally clean in Baudline.
![sine_audacity](https://user-images.githubusercontent.com/6670911/43044126-f6465a64-8da0-11e8-9c35-421183bf70d1.png)
2. imported the sine into Samplv1 with settings that should not add harmonics.
![samplv1](https://user-images.githubusercontent.com/6670911/43044141-34e0414a-8da1-11e8-854b-8625f3bd9c22.png)
3. played Samplev1 at its rootkey but get all those harmonics.
![sine_samplv1](https://user-images.githubusercontent.com/6670911/43044149-55224a2a-8da1-11e8-8f82-4e8e051b1504.png)
This shows the 220 Hz sine as generated by Audacity, but also a 3 x 220Hz, 5 x 220Hz, 7 x 220Hz. They do have less amplitude, but are still very present.

I wonder if Samplv1 can be improved so that it reproduces the 220Hz sinewave without distortion?
However, if this is "normal" behavior for a sampler, could you please provide a small explanatiion?

The sine wave of 3 seconds is attached.
[sine.wav.zip](https://github.com/rncbc/samplv1/files/2216869/sine.wav.zip)

**Comment by rncbc** [comment]
hi

most probably the root cause is having the "DYN Limiter" turned on, as
is by default.

also, some aliasing introduced due to the sample-rate conversion on load
if the sample-rate of the file (.wav) is of different than the running
processing one (as of jackd).

byee

**Comment by tjingboem** [comment]
> most probably the root cause is having the "DYN Limiter" turned on, as is by default.

Partially true. i have made a video (attached) and have set a loop around the entire sample
[Limit-2018-07-22_15.19.31.mp4.zip](https://github.com/rncbc/samplv1/files/2217053/Limit-2018-07-22_15.19.31.mp4.zip)
;
1. Limiter = off, velocity =  64 (start of video) --> 3 harmonics
2. Limiter = on, velocity =  64 (at 28 seconds) --> 3 harmonics
3. Limiter = on, velocity = 127 (at 52 seconds) --> 5 harmonics
4. Limiter = off, velocity = 127 (at 116 seconds) --> 3 harmonics

So: Limiter does add extra distortion when amplitude is at full power. Normal behavior i would say.

>also, some aliasing introduced due to the sample-rate conversion on load if the sample-rate of the file >(.wav) is of different than the running processing one (as of jackd).

The sine is generated using Audacity at 48kHz and is without distortion. I run Jack so my whole system runs at 48kHz. No conversion of the sample is needed...

I hope i don't bug you too much with this issue  - don't shoot the messenger :)
