### ISSUE TITLE
Ubuntu, Ardour, KXStudios: old problem, new flavour

### ISSUE THREAD

**Issue by sjaehn** [rncbc/samplv1#29]
I'm one of the Ubuntu 18.04 / KxStudios / Ardour 5.12 users who can't get the VeeOne plugins running in their DAW. 

I just updated from 0.9.2 where the GUI didn't work to 0.9.11.

In 0.9.2 I got the message:
`suil error: Unable to open UI library /usr/lib/lv2/samplv1.lv2/samplv1_ui.so (/usr/lib/x86_64-linux-gnu/libQt5Gui.so.5: undefined symbol: hb_font_funcs_set_nominal_glyph_func)`

In 0.9.11 I get the same message now from lilv:
`lilv_lib_open(): error: Failed to open library /usr/lib/lv2/samplv1.lv2/samplv1.so (/usr/lib/x86_64-linux-gnu/libQt5Gui.so.5: undefined symbol: hb_font_funcs_set_nominal_glyph_func)`

And this prevents Ardour even to start the plugin DSP.

In jalv everything is fine. With the notable exception of a segfault I observed.

**Comment by rncbc** [comment]
long known problem.

workarounds:
1) build your own ardour 5.12 over the ubuntu 18.04 (bionic) system libraries;
2) build the vee-ones against the **qtbase5-static** libraries;
3) update the [kxstudio repos](https://kx.studio/Repositories) and install any of vee-ones(`-lv2`) from there; OR
4) add one of my own [Launchpad PPA](https://launchpad.net/~rncbc)'s to your apt sources; eg.:
```
sudo add-apt-repository ppa:rncbc/bionic
sudo apt-get update
sudo apt-get install samplv1-lv2
```
Note that either 3) and 4) do provide the same result as if route 2) is taken; though 4) will end with the very latest and greatest snapshots from yours truly upstream. Remember to uninstall first any existing or previously installed vee-one that you have around (esp. if you built before from source and possibly are deployed under `/usr/local/lib/lv2/`...?).

hth.
cheers

**Comment by sjaehn** [comment]
Thanks for the quick response :-)
