### ISSUE TITLE
add sample browser with autoplay

### ISSUE THREAD

**Issue by p-k-l** [rncbc/samplv1#32]
Hello
please add a simple sample browser to samplv for speed up work with it

best

**Comment by rncbc** [comment]
I beg to disagree with this severely bloalting addition:)

use your file-manager of choice and then just drag-n-drop over the samplv1 GUI instance as you please...
simple as that

cheers

**Comment by p-k-l** [comment]
@rncbc  thanks for replay  
hey linux file manager dont have a autoplay option
