### ISSUE TITLE
LV2 parameter state not handled properly

### ISSUE THREAD

**Issue by falkTX** [rncbc/samplv1#33]
Hello.

As I am investing some time on proper lv2 parameter support in Carla and mod-host, I have seen a LOT of stuff that simply does not work all around the LV2 plugins.
I think the fault was the incomplete plugin support, beginning with the actual official LV2 example plugins.
Been trying to fix the situation, eg-sampler is fixed at https://github.com/lv2/lv2/pull/51
This helped to use as working example plugin (plus I found openmusickontroller plugins like sherlock also work well).

On samplv1 side, the issue is that all the lv2 parameters values are not saved, only the filename for the sample.
(Maybe, like me, you expected the host to be the one having to save such values, but this is incorrect)

The value for these non-control-port properties needs to be saved by the plugin as part of the state. Otherwise LV2 presets will be broken, if you think about it.

Me and Bram (from MOD) are looking into using this plugin, so we can submit a PR for review.
If you rather take care of this yourself, please let us know, thanks!

**Comment by rncbc** [comment]
all lv2 parameters have been saved since,... ever.
care to show some  evidences to counter argument on that?

cf. https://github.com/rncbc/samplv1/blob/729fcc878afdfa022a1707d5353cf532009a6699/src/samplv1_lv2.cpp#L580

**Comment by falkTX** [comment]
hmm I guess I was confused because without loading a file, all other state is not saved.
I assumed that it would not be the case, where all parameters are kept.

seems all good!
