### ISSUE TITLE
Cannot resize oversized samplv1 window

### ISSUE THREAD

**Issue by hellocatfood** [rncbc/samplv1#37]
I have install samplv1 0.9.25.5git.5154d8-66.1 from [this ppa](https://launchpad.net/~rncbc/+archive/ubuntu/apps-impish) on Ubuntu 21.10

I'm attempting to load the plugin in Carla (2.4.3). The plugin appears to load fine but when I then try to load the gui it is oversized and glitches a lot. When I try to resize the window it goes back to its original size and then eventually crashes Carla. I've provided a video below

https://user-images.githubusercontent.com/151947/165333282-ef1eba0a-f217-44a6-afb0-66d6f20a141c.mp4

**Comment by rncbc** [comment]
that's way far from a normal window size as for the samplv1 GUI -- I wonder what carla is tryng to do? is it always trying to make it full-screen? wrong! please review your (carla) settings, perhaps, and do not allow for that! samplv1 window size should be fixed anyway (but I indulged on some way to make it resizable for some freaks out there :)) I guess you're overdoing the freaky-way :D

ps. or is it your WM that is freaky fooling you out? (is it a tiling one?)

pps. idk what you mean with its "original" size, but I'm quite sure it is not full-screen nor maximized as it looks on your screencast.

**Comment by hellocatfood** [comment]
There aren't any setting for scaling of UIs in Carla. Other plugins I load don't try to resize to fit the screen.

Window manager is Gnome Shell. Not a tiling window manager.

By original size I mean the "oversized" size it first loads the plugin at.

**Comment by hellocatfood** [comment]
Just discovered something interesting.

My display size as shown in the original message is 3840x2400 (16:10) at 200% scale. If I change my display size to 1920x1200 (16:10) at 100% scale and try to open samplv1 in carla in loads at the correct size.

No idea which software is having issues with hidpi screens here.

**Comment by rncbc** [comment]
no idea here too, but I still suspect carla

try the standalone for  ours souls sake (samplv1_jack)

**Comment by hellocatfood** [comment]
as you suspected seems like it's something to do with Carla. I shall go and report a bug there
