### ISSUE TITLE
lv2 plugin crashes when trying to load a sample

### ISSUE THREAD

**Issue by groundCover** [rncbc/samplv1#4]
When trying to load a sample in the lv2 samplv1 plugin the GUI crashes. After unchecking "Use desktop environment native dialogs" it doesn't crash anymore.

This issue applies to 0.8.0, 0.7.5 and 0.7.4. I didn't try this with other versions.

I am using Gnome shell.

I could create a gdb dump if you want.

**Comment by rncbc** [comment]
On 11/21/2016 03:06 AM, groundCover wrote:

> When trying to load a sample in the lv2 samplv1 plugin the GUI crashes.
> After unchecking "Use desktop environment native dialogs" it doesn't
> crash anymore.
> 
> This issue applies to 0.8.0, 0.7.5 and 0.7.4. I didn't tried this with
> other versions.
> 
> I am using Gnome shell.
> 
> I could create a gdb dump if you want.

no need for further investigation: it's an old and known issue and one
of the reasons the "use desktop environment native dialogs" is there for
mitigation :)

## byee

rncbc aka. Rui Nuno Capela
rncbc@rncbc.org

**Comment by groundCover** [comment]
You could uncheck the checkbox per default if XDG_CURRENT_DESKTOP=GNOME

**Comment by rncbc** [comment]
On 11/21/2016 03:04 PM, groundCover wrote:

> You could uncheck the checkbox per default iff XDG_CURRENT_DESKTOP=GNOME

that is an awesome hint, thanks

only that might not be enough for all or any cases, and also this is all
an emerging trouble over an incoming gtk2 to gtk3 transition, so things
might just not be that simple anymore, on the near future at least :)

anyhow, the issues at stake (gtk vs. qt coexistence) are way too many to
number, and believe me, qt has been playing the good samaritan for
quite a while (eg. qt-gui/widget applications integrates with glib
event-loop alright; problem comes when you mix gtk2 and gtk3 within...
immediate crash for sure!)

## byee

rncbc aka. Rui Nuno Capela
rncbc@rncbc.org
