### ISSUE TITLE
Looping automation is heavy

### ISSUE THREAD

**Issue by tjingboem** [rncbc/samplv1#43]
i try to automate the loop start and loop end of the sampler, but find that it is very heavy on CPU. 

I work with Reaper on Linux. There is a sampler VSTi plugin that Reaper comes with. There i see no heavy CPU consumption when loop start and loop end are modulated.

[moveLoopStartmp4-2024-12-10_09.54.36.zip](https://github.com/user-attachments/files/18076231/moveLoopStartmp4-2024-12-10_09.54.36.zip)

Disadvantage of the Reaper sampler is, among other things, the lack of filters. In your sampler, the DCF ADSR curves are applied to every note, the Reaper sampler DCF is absent. Adding a filter as an FX would work globally, not locally.

Can this be solved so that all parameters of Samplv1 can be modulated better?

(I am happy with the import option of Scala files, this works great!)

**Comment by rncbc** [comment]
let's start that, in LV2 plugin format, some parameters are not really suitable for free **continuous** automation/modulation, moreover when the control-rate is higher than a few values per second--each data point may incur IPC exchange and expensive thread context-switching, not only some DSP recalculation... it also depends on the specific parameters and plugin implementation... 

let alone it's not that of a wise move to modulate the loop points in any other way than discrete changes, sporadically from time to time...

just out of curiosity, what are you trying to achieve with that? sound-wise, may I ask? loop-points are inherently meant to be kinda static, as they are only meaningful when the sample note playback reaches the loop-end point; rapidly changing loop start/end locations doesn't make much sense to me at least:)

**Comment by tjingboem** [comment]
I have a background of exploring Csound, where, for example, the flooper opcode allows to change parameters including loop points, can be set at k-rate

asig1[,asig2] flooper2 kamp, kpitch, kloopstart, kloopend, kcrossfade, ifn \
      [, istart, imode, ifenv, iskip]

I am looking to get back to Reaper and thus Midi. I am in the process of checking out the limits of what VST instruments can do related to Csound options.

I understand that Reaper and Midi is mostly geared to making pop music, but I am not so much looking to make 'traditional' pop music, but more abstract soundscapes. Musique-concrete.
Then it is interesting to have some variation and modulation of the normally 'static' sample. There is so much more interest in a sample where loop points are variable. This gives each note its own character.

I am also the person that was asking a while back to import Scala tuning files into Samplv1. And Padtv1.
This works well and allows me to make dense clusters of sounds where, for example, one octave is divided into 96 pitches.

**Comment by tjingboem** [comment]
crude example with Reapers sampler
[moveLoopStart2mp4-2024-12-10_15.32.58.zip](https://github.com/user-attachments/files/18081090/moveLoopStart2mp4-2024-12-10_15.32.58.zip)

**Comment by rncbc** [comment]
I'm not arguing whether or not is possible, just that it's a quite expensive **and** totally a waste of (a lot cpu/dsp) real-time to modulate the loop-points, and probably rather meaningless when no notes are even being played.

**Comment by tjingboem** [comment]
As for Samplv1 functions right now, yes, for sure it is not clever to put even more load on CPU usage. 
I wondered why the implementation in Reapers sampler can do this without straining the CPU. It is not open source and we can not look at the code...

As i said, i am checking where the boundaries are in the VST/LV2 Midi world. I have yet to find a sampler that can vary looping points AND have a filter on the note.

Perhaps, at a later time, i will have to build this myself using Csound code. And then use Cabbage to turn this into a VST.

Here is a screenshot of the Csound instrument i built, using the flooper opcode, in a DAW called Blue:
![Screenshot from 2024-12-10 19-38-37](https://github.com/user-attachments/assets/8620c04e-0205-4eba-ac27-a2bf6c6a0d8e)

This DAW Blue is not very developed. This is the reason i may have to return to the Midi environment and Reaper.

**Comment by rncbc** [comment]
please take notice that is the **continuously varying** loop points that are the _nonsensical_ part; besides, it might be just as expensive **especially** if you keep the GUI shown up--don't know if you have the choice not to in reaper--it prolly gets a bit lesser of a burden to the cpu if the GUI is not hosed to redraw the sample waveform on every dang change, got it?

**Comment by tjingboem** [comment]
In the Csound instrument there is no GUI showing the waveform. let alone rapidly moving lines- so no visual updating.
And no printing is done to the output terminal, that is also CPU expensive.

But all is fine, i just wondered why Reapers sampler is able (up to a point where i hear artifacts) to change loop points dynamically. And whether this behavior could be copied over to Samplv1. 

And the answer is no, and that is okay.

i will close the issue now. Thanks for your replies and attention!
